/* Workout App service worker — offline-first app shell cache.
 * Generated by make-sw.py; do not hand-edit (version 20260923-011939). */
const SW_VERSION = "20260923-011939";
const CACHE_NAME = "workout-app-" + SW_VERSION;
const ASSETS = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "icon-180.png",
    "icon-192.png",
    "icon-512.png",
    "favicon.ico",
    "og-card.png",
    "share-card-home-1200.png",
    "assets/styles.css",
    "assets/workout-history-template.csv",
    "data/exercises-db.js",
    "data/exercise-aliases.js",
    "data/sasha-male-body.svg",
    "assets/js/build-info.js",
    "assets/js/data/catalog.js",
    "assets/js/data/custom-exercises.js",
    "assets/js/data/exercise-data.js",
    "assets/js/components/empty-states.js",
    "assets/js/pages/dashboard-stats.js",
    "assets/js/pages/exercise-detail.js",
    "assets/js/pages/exercise-library.js",
    "assets/js/pages/onboarding.js",
    "assets/js/pages/programs.js",
    "assets/js/pages/saved-workouts.js",
    "assets/js/core/app-bootstrap.js",
    "assets/js/core/app-updates.js",
    "assets/js/core/csv-import.js",
    "assets/js/core/navigation.js",
    "assets/js/core/persistence.js",
    "assets/js/core/state.js",
    "assets/js/core/storage.js",
    "assets/js/lib/utilities.js",
    "assets/js/share/share-codec.js",
    "assets/js/share/share.js",
    "assets/js/formulas/e1rm.js",
    "assets/js/formulas/increments.js",
    "assets/js/formulas/program-math.js",
    "assets/js/formulas/progression-analysis.js",
    "assets/js/formulas/prs.js",
    "assets/js/formulas/rpe.js",
    "assets/js/formulas/units.js",
    "assets/js/formulas/volume.js",
    "assets/js/workout/exercise-metrics.js",
    "assets/js/workout/progression.js",
    "assets/js/workout/set-tags.js",
    "assets/js/workout/supersets.js",
    "assets/js/workout/workout-builder.js",
    "assets/js/workout/workout-editor.js",
    "assets/js/workout/workout-history.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      /* Per-asset add under allSettled (user 2026-09-11): addAll is
         all-or-nothing, so one flaky fetch on cellular silently pinned the
         old version. A partial install is safe — the fetch handler falls
         back to network on a cache miss. cache:'reload' bypasses the HTTP
         cache (GitHub Pages sends max-age=600), so a fast follow-up build
         can't precache stale assets. */
      .then((cache) =>
        Promise.allSettled(
          ASSETS.map((u) => cache.add(new Request(u, {cache: "reload"})))
        )
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("workout-app-") && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(
      (hit) =>
        hit ||
        fetch(event.request)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
            }
            return res;
          })
          .catch((err) => {
            /* The index.html fallback is for navigations only (user
               2026-09-11): a failed JS/data fetch resolving with HTML and
               status 200 broke version probes and confused debugging. */
            if (event.request.mode === "navigate") return caches.match("index.html");
            throw err;
          })
    )
  );
});
